# Generated by Django 4.2.1 on 2023-05-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quote", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="threedmodel",
            name="model_file",
            field=models.FileField(upload_to="static/uploads/"),
        ),
    ]
