# Generated by Django 4.2.1 on 2023-05-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quote", "0002_alter_threedmodel_model_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="threedmodel",
            name="custom",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="threedmodel",
            name="material",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="threedmodel",
            name="notes",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="threedmodel",
            name="tolerance",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
