# Generated by Django 4.2.1 on 2023-05-22 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quote", "0003_threedmodel_custom_threedmodel_material_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fast", models.CharField(blank=True, max_length=255, null=True)),
                ("normal", models.CharField(blank=True, max_length=255, null=True)),
                ("economy", models.CharField(blank=True, max_length=255, null=True)),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
                ("uniqueId", models.CharField(blank=True, max_length=100, null=True)),
                ("date_created", models.DateTimeField(blank=True, null=True)),
                (
                    "model",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quote.threedmodel",
                    ),
                ),
            ],
        ),
    ]
