# Generated by Django 4.2.1 on 2023-05-22 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quote", "0004_quote"),
    ]

    operations = [
        migrations.RemoveField(model_name="quote", name="model",),
        migrations.AddField(
            model_name="quote",
            name="threeDModel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quote.threedmodel",
            ),
        ),
    ]
