# Generated by Django 4.2.1 on 2023-05-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quote", "0005_remove_quote_model_quote_threedmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="threedmodel",
            name="economy",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="threedmodel",
            name="fast",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="threedmodel",
            name="normal",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(name="Quote",),
    ]
